### ISSUE TITLE
AnimeSearch

### ISSUE THREAD

**Issue by EloMonarch** [darenliang/mal-api#11]
from mal import *

anime = AnimeSearch('Seven deadly sins')
print(anime.results[0].title)

when I put in "Seven Deadly Sins" it just breaks, but it works for anything else I've tried.. any ideas?

**Comment by darenliang** [comment]
Could you provide an error message?

**Comment by EloMonarch** [comment]
That's the whole thing:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mal\anime_search.py", line 49, in results
    self._results
AttributeError: 'AnimeSearch' object has no attribute '_results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\PC\Desktop\asfsf.py", line 4, in <module>
    print(anime.results[0].title)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mal\anime_search.py", line 63, in results
    image_url=self._extract_image_url(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\mal\search.py", line 66, in _extract_image_url
    f"https://cdn.myanimelist.net/images/"
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by EloMonarch** [comment]
Just tried putting "anime" at the end so: "sevend deadly sins anime", and it worked, is this a bug or..?

**Comment by darenliang** [comment]
I don't think that is possible as MyAnimeList doesn't expose that kind of information.

However, you'll be able to estimate the number of seasons an anime has by using `.related_anime`.

`.related_anime["Prequel"]` returns the prequel
`.related_anime["Sequel"]` returns the sequel

You can try printing the attribute and figuring out what can be used.
